service: pugzy

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-central-1
  memorySize: 264
  timeout: 15
  environment:
    NODE_ENV: production
    LAMBDA: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

package:
  exclude:
    - .git/**

plugins:
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-plugin-warmup

custom:
  stage: ${opt:stage, self:provider.stage}
  domain:
    dev: dev.example.com
    prod: prod.example.com
  customDomain:
    enabled: true
    stage: ${self:custom.stage}
    domainName: ${self:custom.domain.${self:custom.stage}}
    certificateName: '*.example.com'
    basePath: ''
    createRoute53Record: true
    endpointType: regional
  apigwBinary:
    types:
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}
    warmup: true